@startuml adcionar_aluno
skinparam sequenceParticipant underline

actor ":Professor" as Professor
boundary ":TelaCadastroAluno" as TelaCadastroAluno
control ":CtrCadastroAluno" as CtrCadastroAluno
entity ":Turma" as Turma
entity ":Cadastro" as Cadastro

Professor -> TelaCadastroAluno : informarDados()
TelaCadastroAluno -> CtrCadastroAluno : cadastrarDados()
CtrCadastroAluno -> Turma : PesquisarAluno()
CtrCadastroAluno -> Cadastro : criarAlunoIndividual(dados,turma)
CtrCadastroAluno --> TelaCadastroAluno : AlunoCadastrado

@enduml