@startuml alterar_professor
skinparam sequenceParticipant underline

actor ":Professor" as Professor
boundary ":TelaPerfilProfessor" as TelaPerfilProfessor
control ":CtrProfessor" as CtrProfessor
entity ":validacao" as validacao
entity ":professor" as professor



Professor -> TelaPerfilProfessor : 1: acessarPerfil
Professor -> TelaPerfilProfessor : 2: alteraDados
TelaPerfilProfessor -> CtrProfessor : 3: enviaDados()
CtrProfessor -> validacao: 4: validaDados()
CtrProfessor -> professor : 5: modificaDados()
CtrProfessor --> TelaPerfilProfessor --: 6: Sucesso na Alteração


@enduml 