@startuml alterar_aluno
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
boundary ":TelaPerfilAluno" as TelaPerfilAluno
control ":CtrAluno" as CtrAluno
entity ":aluno" as aluno



Aluno -> TelaPerfilAluno : informaDados()
TelaPerfilAluno -> CtrAluno : enviaDados()
CtrAluno -> aluno : PesquisaAluno(dados)
aluno -> aluno : ModificaAluno(dados_novos)
CtrAluno --> TelaPerfilAluno --: Sucesso na Alteração


@enduml