@startuml
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
boundary ":TelaInicialAluno" as TelaInicialAluno
boundary ":TelaTurmaAluno" as TelaTurmaAluno
boundary ":TelaAtualizarProjeto" as TelaAtualizarProjeto
boundary ":TelaNotificacao" as TelaNotificacao
control ":ManutencaoProjeto" as ManutencaoProjeto
entity ":Projeto" as Projeto

ref over Aluno : sdEfetuarLogin

Aluno -> TelaInicialAluno : acessa o sistema
TelaInicialAluno ->> TelaTurmaAluno : acessarTurma()
TelaTurmaAluno --> Aluno : exibirTelaAtualizarProjeto()
Aluno ->> TelaAtualizarProjeto : informarDados()
Aluno -> TelaAtualizarProjeto : confirmarEnvio()

TelaAtualizarProjeto -> ManutencaoProjeto : efetuarMudancas()
ManutencaoProjeto -> Projeto : persistirMudanças()
Projeto --> ManutencaoProjeto : informa o resultado das mudanças
ManutencaoProjeto ->> TelaNotificacao : notificarMembros()
TelaNotificacao --> Aluno : notificarMembros()
@enduml
