@startuml alterar_projeto
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
boundary ":TelaProjeto" as TelaProjeto
boundary ":TelaAtualizarProjeto" as TelaAtualizarProjeto
control ":ManutencaoProjeto" as ManutencaoProjeto
entity ":Projeto" as Projeto


Aluno ->> TelaProjeto : 1: acessar o projeto
Aluno ->> TelaAtualizarProjeto : 2: acessar formulario de atualização
Aluno -> TelaAtualizarProjeto : 3: alterarDados()

TelaAtualizarProjeto -> ManutencaoProjeto : 4: enviarDados()

alt Dados Válidos
    ManutencaoProjeto -> Projeto : 5: modificaDados()
    ManutencaoProjeto -->> TelaProjeto --: 6: Sucesso na Alteração
else Dados Invalidos
    ManutencaoProjeto -> Projeto : 5: modificaDados()
    ManutencaoProjeto -->> TelaProjeto --: 6: Insucesso na Alteração
end

@enduml