@startuml alterar_aluno
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
boundary ":TelaPerfilAluno" as TelaPerfilAluno
control ":CtrAluno" as CtrAluno
entity ":validacao" as validacao
entity ":aluno" as aluno



Aluno -> TelaPerfilAluno : 1: acessarPerfil
Aluno -> TelaPerfilAluno : 2: alteraDados
TelaPerfilAluno -> CtrAluno : 3: enviaDados()
CtrAluno -> validacao: 4: alidaDados()
CtrAluno -> aluno : 5: modificaDados()
CtrAluno --> TelaPerfilAluno --: 6: Sucesso na Alteração


@enduml