@startuml
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
boundary ":TelaAlterarProjeto" as TelaAlterarProjeto
control ":CtrAlterarProjeto" as CtrAlterarProjeto
entity ":Projeto" as Projeto


Aluno ->> TelaProjeto : 1: acessar o projeto
Aluno ->> TelaAlterarProjeto : 2: acessar formulario de atualização
Aluno -> TelaAlterarProjeto : 3: alterarDados()

TelaAlterarProjeto -> CtrAlterarProjeto : 4: enviarDados()

alt Dados Válidos
    CtrAlterarProjeto -> Projeto : 5: modificaDados()
    CtrAlterarProjeto -->> TelaProjeto --: 6: Sucesso na Alteração
else Dados Invalidos
    CtrAlterarProjeto -> Projeto : 5: modificaDados()
    CtrAlterarProjeto -->> TelaProjeto --: 6: Insucesso na Alteração
end

@enduml
