@startuml
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
actor ":Professor" as Professor
boundary ":TelaInicialProfessor" as TelaInicialProfessor
boundary ":TelaTurmaProfessor" as TelaTurmaProfessor
boundary ":TelaAvaliacao" as TelaAvaliacao
boundary ":TelaNotificacao" as TelaNotificacao
control ":ControladorAvaliacao" as ControladorAvaliacao
entity ":Projeto" as Projeto

ref over Aluno, Professor : sdProporProjeto

Professor -> TelaInicialProfessor ++: acessa o sistema
TelaInicialProfessor --> Professor --: exibirTelaTurma()
Professor -> TelaTurmaProfessor  ++: verPropostas()
TelaTurmaProfessor --> Professor : exibirPropostas()
Professor -> TelaTurmaProfessor : avaliarProposta()
TelaTurmaProfessor --> Professor : exibirTelaAvaliacao()
destroy TelaTurmaProfessor

Professor -\\ TelaAvaliacao ++: confirmarAvaliacao()
TelaAvaliacao -> ControladorAvaliacao --++: enviarAvaliacao()
alt aprovado
  ControladorAvaliacao ->> Projeto : construirProjeto()
else não aprovado
  ControladorAvaliacao ->> ControladorAvaliacao : rejeitarProposta()
end
ControladorAvaliacao -\\ TelaNotificacao --: notificarMembros()
TelaNotificacao ->> Aluno --: exibeNotificacoes()
@enduml
