@startuml
skinparam sequenceParticipant underline

actor ":Professor" as Professor
boundary ":TelaAvaliarProposta" as TelaAvaliarProposta
control ":CtrAvaliarProposta" as CtrAvaliarProposta
entity ":Projeto" as Projeto
entity ":Avaliacao" as Avaliacao
entity ":PropostaProjeto" as PropostaProjeto

Professor -> TelaAvaliarProposta : 1: informar avaliacao
TelaAvaliarProposta -> CtrAvaliarProposta : 2: avaliarProposta()
CtrAvaliarProposta -> Avaliacao : 3: aprovado := verificaProposta()
alt aprovado
  CtrAvaliarProposta ->> Projeto ** : 4: <<create>>
  CtrAvaliarProposta ->> PropostaProjeto !! : 5: <<destroy>>
else não aprovado
  CtrAvaliarProposta ->> CtrAvaliarProposta : 4: rejeitarProposta()
end
TelaAvaliarProposta <<-- CtrAvaliarProposta : 5: proposta avaliada
@enduml
