@startuml
skinparam sequenceParticipant underline

actor ":Interessado" as Interessado
boundary ":TelaConsultarProjeto" as TelaConsultarProjeto
control ":CtrConsultarProjeto" as CtrConsultarProjeto
entity ":Projeto" as Projeto

Interessado -> TelaConsultarProjeto : 1: informar dados
TelaConsultarProjeto -> CtrConsultarProjeto : 2: processarConsulta(dados)
CtrConsultarProjeto -> Projeto : 3: *verificarCumpreCriterios(dados)
TelaConsultarProjeto <<-- CtrConsultarProjeto : 4: exibe os resultados
@enduml
