@startuml criar_Turma
skinparam sequenceParticipant underline

actor ":Professor"  as Professor
boundary ":TelaCadastro"    as TelaCadastro
control ":ControleTurma" as ControleTurma
entity "novaTurma:Turma" as novaTurma

Professor -> TelaCadastro : 1: inserir dados
TelaCadastro -> ControleTurma : 2: criarTurma(dadosTurma)
ControleTurma -> novaTurma **: 3: <<create>>

ControleTurma --> TelaCadastro : 4: turma criada
@enduml