@startuml
skinparam sequenceParticipant underline

actor ":Professor"  as Professor
boundary ":TelaCadastro"    as TelaCadastro
control ":ControleTurma" as ControleTurma
entity "novaTurma:Turma" as novaTurma
database Banco

Professor -> TelaCadastro : 1: insereDados
TelaCadastro -> ControleTurma : 2: enviaDados(dadosTurma)
ControleTurma -> novaTurma **: 3: <<create>>
novaTurma -> Banco : 4: registraBanco(dadosTurma)
ControleTurma --> TelaCadastro : 5: turmaCriada
@enduml