@startuml
skinparam sequenceParticipant underline

actor ":Professor"  as Professor
boundary ":TelaCriarTurma" as TelaCriarTurma
control ":CtrCriarTurma" as CtrCriarTurma
entity "novaTurma:Turma" as novaTurma

Professor -> TelaCriarTurma : 1: inserir dados
TelaCriarTurma -> CtrCriarTurma : 2: criarTurma(dadosTurma)
CtrCriarTurma -> novaTurma **: 3: <<create>>

CtrCriarTurma --> TelaCriarTurma : 4: turma criada
@enduml
