@startuml
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
boundary ":TelaEscolherProjeto" as TelaEscolherProjeto
control ":CtrEscolhaProjeto" as CtrEscolhaProjeto
entity "grupo:Grupo" as Grupo
entity ":Projeto" as Projeto

Aluno -> TelaEscolherProjeto: : 1: informar escolha
TelaEscolherProjeto -> CtrEscolhaProjeto : 2: escolherProjeto()
CtrEscolhaProjeto ->> Grupo ** : <<create>>
CtrEscolhaProjeto -> Projeto : 4: adicionarGrupo(grupo)
TelaEscolherProjeto <<-- CtrEscolhaProjeto : 5: escolha efetivada
@enduml
