@startuml
skinparam sequenceParticipant underline

actor ":Professor"  as Professor
boundary ":TelaLogin"   as TelaLogin
boundary ":TelaCadastroAluno"    as TelaCadastroAluno
control ":ControleAluno" as ControleAluno
entity "novoAluno:Aluno" as novoAluno
database Banco

ref over Professor, TelaLogin : sdEfetuarLogin

Professor -> TelaCadastroAluno ++: informarDados()
TelaCadastroAluno -> ControleAluno ++: enviarDados()
ControleAluno -> novoAluno ++: criarAlunoIndividual()
novoAluno -> Banco : registraBanco()
Banco --> novoAluno : resultado da inserção
novoAluno --> ControleAluno --: notificaResultado()
destroy novoAluno
ControleAluno --> TelaCadastroAluno --: notificaResultado()

alt cadastro realizado
    TelaCadastroAluno --> Professor : informaSucesso()
else erro de cadastro
    TelaCadastroAluno --> Professor : informaFalha()
end
@enduml
