@startuml
skinparam sequenceParticipant underline

actor ":Aluno" as Aluno
boundary ":TelaInicial" as TelaInicial
boundary ":TelaProjeto" as TelaProjeto
participant ":Projeto" as Projeto

ref over Aluno : sdEfetuarLogin

alt se for criar
    Professor -> TelaInicial : criarProjeto()
else se for modificar
    Aluno -> TelaInicial : verProjeto()
    TelaInicial --> Aluno : exibeTelaProjeto()
    Aluno -> TelaProjeto : mudarProjeto()
end

TelaProjeto -> Projeto : efetuarProjeto()
Projeto -> Projeto : persisteMudanças()
Projeto -\\ TelaProjeto : notificaMembros()
TelaProjeto --> Aluno : notificaMudanca()
@enduml
