@startuml oferta
skinparam sequenceParticipant underline

actor ":Professor" as Professor
boundary ":TelaOferta" as TelaOferta
control ":ControladorOferta" as ControladorOferta
entity ":Oferta" as Oferta
entity ":Turma" as Turma

Professor -> TelaOferta :1: informarDados()
TelaOferta -> ControladorOferta :2: regOferta()
ControladorOferta -> Oferta :3: valOferta(Dados)
Oferta -> Turma :4: pesquisarTurma()
ControladorOferta -> Turma :5: registrarOferta(Oferta)

ControladorOferta -->> TelaOferta --:6: OfertaRegistrada
@enduml