@startuml

!includesub base.puml!Projeto
!includesub base.puml!Avaliacao
!includesub base_telas.puml!TelaNotificacao
!includesub base_telas.puml!TelaTurmaProfessor

class TelaAvaliacao <<boundary>> {
  confirmarAvaliacao()
  enviarAvaliacao()
}

class ControladorAvaliacao <<control>> {
  construirProjeto()
  verificaProposta()
}

TelaAvaliacao -- TelaTurmaProfessor
ControladorAvaliacao -- TelaAvaliacao
ControladorAvaliacao -- Projeto
ControladorAvaliacao -- Avaliacao
ControladorAvaliacao -- TelaNotificacao

@enduml
