@startuml 
' Muitas dessas classes estão envoltas nos macros de start/endsub pois
' queremos permitir include seletivo de classes em outros diagramas de classes
' de alguns casos de uso.
!startsub Departamento
class Departamento <<entity>> {
  nome: String
}
!endsub

!startsub Disciplina
class Disciplina <<entity>> {
  nome: String
  codigo: String
}
!endsub

!startsub Professor
class Professor <<entity>> {
  nome: String
  dataNasc: Date
  matricula: String
}
!endsub

!startsub Aluno
class Aluno <<entity>> {
  nome: String
  dataNasc: Date
  matricula: String
  curso: String
}
!endsub

!startsub Grupo
class Grupo <<entity>> {
}
!endsub

!startsub StatusProjeto
enum StatusProjeto <<enumeration>> {
  concluido
  cancelado
  suspenso
}
!endsub

!startsub ProjetoAbstrato
abstract class ProjetoAbstrato <<entity>> {
  titulo: String
  descricao: String
  tags: String[]
  documentos: File[]
}
!endsub

!startsub Projeto
class Projeto <<entity>> {
  dataCriado: Date
  adicionarMembros()
  persistirMudanças()
}
!endsub

!startsub Turma
class Turma <<entity>> {
  codigo: String
  adicionarProposta()
  adicionarProjeto()
}
!endsub

!startsub PropostaProjeto
class PropostaProjeto <<entity>> {
  dataProposto: Date
}
!endsub

!startsub Avaliacao
class Avaliacao <<entity>> {
  mensagem: String
}
!endsub

!startsub StatusAvaliacao
enum StatusAvaliacao <<enumeration>> {
  aprovado
  rejeitado
  melhorias
}
!endsub

ProjetoAbstrato <|-- Projeto
ProjetoAbstrato <|-- PropostaProjeto

Avaliacao "0..*" -- "1..1" StatusAvaliacao : possui >
Avaliacao "1..1" -- "1..1" PropostaProjeto : recebe <

Aluno "1..*" -- "0..1" Grupo : forma >
Aluno "0..*" -- "0..*" Turma : estuda >

Grupo "1..1" -- "1..1" Projeto : responsável >

Professor "1..*" -- "1..1" Departamento : trabalha >
Professor "1..*" -- "0..*" Turma : leciona >

Departamento "1..1" -- "1..*" Disciplina : oferta >

Turma "0..*" -- "1..1" Disciplina : instância de >

Projeto "0..*" -- "1..1" StatusProjeto : possui >
@enduml
