@startuml
!includesub base.puml!Projeto

class TelaConsulta <<boundary>> {
  informarTermoConsulta()
  selecionarFiltros()
  exibirFiltros()
  preencherFiltros()
  confirmarConsulta()
}
class TelaResultados <<boundary>> {
  exibeResultados()
}
class Buscador <<control>> {
  processarConsulta()
  verificarVisibilidade()
}

class Filtrador <<control>> {
  cumpreFiltro()
  insereProjeto()
  descartaProjeto()
}

class GeradorResultados <<control>> {
  gerarResultados()
  informarResultados()
}

Buscador -- Filtrador
Filtrador -- GeradorResultados
Buscador -- TelaConsulta
Buscador -- Projeto
GeradorResultados -- TelaResultados
@enduml
