@startuml
!includesub base.puml!Aluno
!includesub base.puml!Turma
!includesub base_telas.puml!TelaTurmaProfessor

class TelaTurmaInclusao <<boundary>> {
  informarDadosIndividual()
  informarDadosLote()
  confirmarEnvio()
}
class ControleTurma <<control>> {
  criarTurma()
  incluirAlunoIndividual()
  incluirAlunoLote()
  notificaResultado()
}

TelaTurmaInclusao -- ControleTurma
TelaTurmaInclusao -- TelaTurmaProfessor
ControleTurma -- Aluno
ControleTurma -- Turma
@enduml
