@startuml

!includesub base.puml!Projeto
!includesub base_telas.puml!TelaTurmaAluno
!includesub base_telas.puml!TelaNotificacao

class TelaEscolhaProjeto <<boundary>> {
  exibirProjetos()
  confirmarEscolha()
  mostrarErro()
}

class ControleEscolhaProjeto <<control>> {
  cadastrarGrupo()
  adicionarMembros()
}

TelaTurmaAluno -- TelaEscolhaProjeto
TelaEscolhaProjeto -- ControleEscolhaProjeto
ControleEscolhaProjeto -- TelaNotificacao
ControleEscolhaProjeto -- Projeto

@enduml
