@startuml

!includesub base.puml!Turma
!includesub base_telas.puml!TelaTurmaProfessor

class TelaOferta <<boundary>> {
  confirmarEnvio()
  cadastrarOferta()
}

class ControladorOferta <<control>> {
  criarOferta()
  validarOferta()
  notificarTurma()
}

TelaOferta -- TelaTurmaProfessor
ControladorOferta -- TelaOferta
ControladorOferta -- Turma
@enduml
