@startuml

!includesub base.puml!Aluno
!includesub base_telas.puml!TelaInicialProfessor
!includesub base_telas.puml!TelaNotificacao
!includesub base_telas.puml!TelaTurmaAluno
!includesub base_telas.puml!TelaTurmaProfessor
!includesub base.puml!Projeto
!includesub base.puml!Avaliacao
!includesub base.puml!Turma
!includesub base.puml!Professor
!includesub base.puml!PropostaProjeto

class TelaCadastroAluno <<boundary>> {
  informarDados()
  enviarDados()
  informarSucesso()
  informarFalha()
}

class TelaAtualizarProjeto <<boundary>> {
  enviarDados()
  confirmarEnvio()
}

class TelaAvaliacao <<boundary>> {
  confirmarAvaliacao()
  enviarAvaliacao()
}

class TelaNotificacao <<boundary>> {
  notificarAvaliacao()
  notificarMembros()
  notificarProposta()
  notificar()
}

class TelaInicialAluno <<boundary>> {
  acessarTurma()
  exibirTelaTurma()
}

class TelaInicialProfessor <<boundary>> {
  acessarTurma()
  exibirTelaTurma()
}

class TelaTurmaAluno <<boundary>> {
  exibirTelaEscolhaProjeto()
  exibirTelaAtualizarProjeto()
  exibirTelaProposta()
}



class TelaTurmaProfessor <<boundary>> {
  exibirTelaAvaliacao()
}

class TelaConsulta <<boundary>> {
  informarTermoConsulta()
  selecionarFiltros()
  exibirFiltros()
  preencherFiltros()
  confirmarConsulta()
}

class TelaResultados <<boundary>> {
  exibeResultados()
}

class TelaTurmaInclusao <<boundary>> {
  informarDadosIndividual()
  informarDadosLote()
  confirmarEnvio()
}

class TelaLogin <<boundary>> {
  enviarCredenciais()
  informarSucesso()
  informarFalha()
}

class TelaEscolhaProjeto <<boundary>> {
  exibirProjetos()
  confirmarEscolha()
  mostrarErro()
}

class TelaOferta <<boundary>> {
  confirmarEnvio()
  cadastrarOferta()
}

class TelaProposta <<boundary>> {
  informarDados()
  confirmarEnvio()
}



class ControleAluno <<control>> {
  criarAlunoIndividual()
  criarAlunoLote()
  notificaResultado()
  modificaDados()
}


class ManutencaoProjeto <<control>> {
  modificarDados()
  notificarMembros()
}



class ControladorAvaliacao <<control>> {
  construirProjeto()
  verificaProposta()
}



class CtrConsultarProjeto <<control>> {
  processarConsulta()
  verificarVisibilidade()
  verificarCriterios()
}



class ControleTurma <<control>> {
  criarTurma()
  incluirAlunoIndividual()
  incluirAlunoLote()
  notificaResultado()
}



class ControleEscolhaProjeto <<control>> {
  cadastrarGrupo()
  adicionarMembros()
}


class ControladorOferta <<control>> {
  criarOferta()
  validarOferta()
  notificarTurma()
}



class ControladorProposta <<control>> {
  registrarProposta()
  adicionarProposta()
  notificarProfessor()
}



TelaCadastroAluno -- ControleAluno
TelaCadastroAluno -- TelaInicialProfessor
ControleAluno -- Aluno
ManutencaoProjeto -- Projeto
TelaAtualizarProjeto -- ManutencaoProjeto
TelaAtualizarProjeto -- TelaNotificacao
TelaAtualizarProjeto -- TelaTurmaAluno
TelaAvaliacao -- TelaTurmaProfessor
ControladorAvaliacao -- TelaAvaliacao
ControladorAvaliacao -- Projeto
ControladorAvaliacao -- Avaliacao
ControladorAvaliacao -- TelaNotificacao
TelaTurmaAluno -- TelaInicialAluno
TelaTurmaProfessor -- TelaInicialProfessor
CtrConsultarProjeto -- TelaConsulta
CtrConsultarProjeto -- Projeto
GeradorResultados -- TelaResultados
TelaTurmaInclusao -- ControleTurma
TelaTurmaInclusao -- TelaTurmaProfessor
ControleTurma -- Aluno
ControleTurma -- Turma
TelaTurmaAluno -- TelaEscolhaProjeto
TelaEscolhaProjeto -- ControleEscolhaProjeto
ControleEscolhaProjeto -- TelaNotificacao
ControleEscolhaProjeto -- Projeto
TelaOferta -- TelaTurmaProfessor
ControladorOferta -- TelaOferta
ControladorOferta -- Turma
TelaProposta -- TelaTurmaAluno
TelaProposta -- ControladorProposta
ControladorProposta -- PropostaProjeto
ControladorProposta -- Turma
ProjetoAbstrato <|-- Projeto
ProjetoAbstrato <|-- PropostaProjeto
Avaliacao "0..*" -- "1..1" StatusAvaliacao : possui >
Avaliacao "1..1" -- "1..1" PropostaProjeto : recebe <
Aluno "1..*" -- "0..1" Grupo : forma >
Grupo "0..*" -- "1..1" Turma : pertence >
Aluno "0..*" -- "0..*" Turma : estuda >
Aluno "1..*" -- "1..1" Curso : cursa >
Professor "1..*" -- "1..1" Departamento : trabalha >
Professor "1..*" -- "0..*" Turma : leciona >
Departamento "1..1" -- "1..*" Disciplina : oferta >
Departamento "1..1" -- "1..*" Curso : pertence <
Turma "0..*" -- "1..1" Disciplina
Projeto "0..*" -- "1..1" StatusProjeto : possui >
Projeto "0..*" -- "1..1" Turma : pertence >

@enduml