@startuml DiagramaDePack

package Entidade{

    class Pessoa{
        -Nome: String
        -Idade: Int
        -CEP: String
        -Numero: String
        -Complemento: String
        -Telefone: String[]
        getNome()
        getCep()
    }

    class Professor {
        -Matricula: String 
        getMatricula
    }

    class Aluno {
        -Matricula: String
        -DataDeEntrada: Data
        getMatricula()
        getData()
    }

    class Gestor {
        -Matricula: String
        getMatricula()
    }

    class Projeto {
        -Titulo: String
        -Descrição: String
        -Status: String
        -Ano: Int
        -Área: String
        -Entrega: Data
        -Autor: String
        -Departamento: String
        informaRevisao()
        efetuarMudancas()
        persisteMudancas()
        efetuarProjeto()
        registrarMembros()
    }

    class turma {
        -codigo: String
        -Disciplina: String
        -Departamento: String
        -Horario: String
        -NumeroSala: Int
        -Semestre: Data
        getCodigo()
        getDisciplina()
        getDepartamento()
    }

    class Proposta{
        -Titulo: String
        -Descrição: String
        -Departamento: String
        -DataEntrega: Data
        -Origem: String
        -Disciplina: String
        -ProfessorResponsavel: String
        -Participantes: String[]
        aprovarProposta()
        rejeitarProposta()
        getTitulo()
        getDescricao()
        getProfessor()

    }

    class Notificacao{
        -data: Data
        -tipo: String
    }

    Pessoa <|-- Professor
    Pessoa <|-- Aluno
    Pessoa <|-- Gestor
}

package Control{
    
    class Buscador  {
     processarBusca()
     insereProjetoNoResultado()
     descartaProjetos()
     gerarResultados()
    }

    class VerificadorLogin{
        VerificaddorCadastro()
    }

    class ControladorProjeto{
        tratarRevisao()
        encontrarProjeto()
    }

    class GerenciadorContas{
        enviaDados()
    }

    class ControladorTurma{
        registrarProposta()
    }
}

package Interface{
    class TelaLogin{
        insereDados()
        informarValidez()
    }

    class TelaInicial{
        verificaNotificações()
        acessarProjeto()
        NotificaAluno()
        acessarTurma()
        criarProjeto()
        verProjeto()
    }

    class TelaTurma{
        verPropostas()
        revisarProposta()
        escolherProjeto()
        proporProjeto()
    }

    class TelaRevisao{
        enviarRevisao()
    }

    class TelaBusca{
        informarTermoBusca()
        selecionarFiltros()
        confirmarBusca()
        informarResultados()
    }

    class TelaEscolhaProjeto{
        informarMembros()
        selecionarProjeto()
    }

    class TelaCadastro{
        insereDados()
    }

    class TelaProjeto{
        mudarProjeto()
        informarDados()
    }

    class TelaProposta{
        informarDados()
    }
}

package BancodeDados{
    class CadastroAluno{
    criaAlunoIndividual()
    informaDados()
}

    class CadastroProfessor{
    criarProfessorIndividual()
    informaDados()
}

    class CadastroTurma{
    criaTurmaIndividual()
    informaDados()
}

    class Sigaa{
    criarAlunoLote()
    criarProfessorLote()
    criarTurmaLote()
}
}

Entidade --> Interface
Interface --> Control
BancodeDados <-- Control



@enduml