@startuml adicionarAluno
|Professor|
start
:Informar Matricula;
:Pesquisar o aluno na Turma; 
:Cadastrar dados do aluno;
:Efetuar Cadastro;
:Adicionar o aluno na Turma;
:Informar aluno;
| Aluno |
:Receber notificação;
stop
@enduml