@startuml
start
if (quer ver potenciais projetos privados?) then (sim)
  :Efetuar Login;
else (não)
endif
repeat
:Acessar tela de consultar projetos;
:Informar dados;
:Informar filtros;
:Mostrar resultados;
repeat while (pesquisar novamente?) is (sim)
->não;
stop
@enduml
