@startuml ofertar_projeto
|Professor|
start
:Acessar turma;
:Escolher ofertar projeto;
:Preencher dados da oferta;
:Enviar oferta;
|Sistema|
:Recebe oferta;
if ()then([Válida])
  :Cadastra como projeto;
  :Adiciona oferta na turma;
  :Exibe confirmação;
  stop
else([Inválida])
  :Informa oferta inválida;
  stop
@enduml