# Generated by Django 4.2.7 on 2024-02-28 16:16

import app.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="admin status",
                    ),
                ),
                (
                    "is_student",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is a student.",
                        verbose_name="student",
                    ),
                ),
                (
                    "is_teacher",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is a teacher.",
                        verbose_name="teacher",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", app.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "matricula",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
                ("curso", models.CharField(max_length=50)),
                ("data_nascimento", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alunos", models.ManyToManyField(to="app.aluno")),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "matricula",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                (
                    "cod_departamento",
                    models.ForeignKey(
                        on_delete=models.SET("Nao existe"), to="app.departamento"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=800)),
                ("data_proposta", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=12)),
                ("ano", models.IntegerField(default=2024)),
                ("periodo", models.IntegerField(default=1)),
                ("alunos", models.ManyToManyField(to="app.aluno")),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.disciplina"
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=800)),
                ("data_criacao", models.DateField()),
                (
                    "status_projeto",
                    models.CharField(
                        choices=[
                            ("CO", "Concluido"),
                            ("CA", "Cancelado"),
                            ("SU", "Suspenso"),
                            ("EP", "Em progresso"),
                        ],
                        default="EP",
                        max_length=2,
                    ),
                ),
                (
                    "cod_grupo",
                    models.OneToOneField(
                        on_delete=models.SET("Nao existe"), to="app.grupo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.CharField(max_length=800)),
                (
                    "status_avaliacao",
                    models.CharField(
                        choices=[
                            ("AP", "Aprovado"),
                            ("RE", "Rejeitado"),
                            ("ME", "Melhorias"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "proposta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.proposta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula_aluno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('curso', models.CharField(max_length=300)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_departamento', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disciplina', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=300)),
                ('cod_departamento', models.ForeignKey(on_delete=models.SET('Nao existe'), to='app.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('cod_grupo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('cod_turma', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('cod_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('cod_proposta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=800)),
                ('data_proposta', models.DateField()),
                ('matricula_aluno', models.ForeignKey(on_delete=models.SET('Naao existe'), to='app.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('cod_projeto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=800)),
                ('data_criacao', models.DateField()),
                ('status_projeto', models.CharField(choices=[('Concluido', 'Concluido'), ('Cancelado', 'Cancelado'), ('Suspenso', 'Suspenso'), ('Em progresso', 'Em Progresso')], default='Em progresso', max_length=20)),
                ('cod_grupo', models.OneToOneField(on_delete=models.SET('Nao existe'), to='app.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('matricula_professor', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('data_nascimento', models.DateField()),
                ('cod_departamento', models.ForeignKey(on_delete=models.SET('Nao existe'), to='app.departamento')),
                ('turmas', models.ManyToManyField(to='app.turma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('cod_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=800)),
                ('status_avaliacao', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado'), ('Melhorias', 'Melhorias')], max_length=20)),
                ('cod_proposta', models.OneToOneField(on_delete=models.SET('Nao existe'), to='app.proposta')),
                ('matricula_professor', models.ForeignKey(on_delete=models.SET('Nao existe'), to='app.professor')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='cod_grupo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Nao existe'), to='app.grupo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(to='app.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
