# Generated by Django 4.2.7 on 2024-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposta",
            old_name="proponente",
            new_name="autor",
        ),
        migrations.AddField(
            model_name="proposta",
            name="tags",
            field=models.CharField(default="", max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proposta",
            name="data_proposta",
            field=models.DateField(auto_now_add=True),
        ),
    ]
