# Generated by Django 4.2.7 on 2024-03-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="membros",
            field=models.ManyToManyField(db_table="forma", to="app.aluno"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="alunos",
            field=models.ManyToManyField(db_table="estuda", to="app.aluno"),
        ),
    ]
