# Generated by Django 4.2.7 on 2024-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is a student.",
                verbose_name="student",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is a teacher.",
                verbose_name="teacher",
            ),
        ),
    ]
