# Generated by Django 4.2.7 on 2024-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_grupo_membros_alter_turma_alunos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="membros",
            field=models.ManyToManyField(db_table="app_forma", to="app.aluno"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="alunos",
            field=models.ManyToManyField(db_table="app_estuda", to="app.aluno"),
        ),
    ]
