# Generated by Django 4.2.7 on 2024-03-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_avaliacao_status_avaliacao_avaliacao_aprovado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grupo",
            old_name="alunos",
            new_name="membros",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="cod_grupo",
            new_name="grupo",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="status_projeto",
            new_name="status",
        ),
        migrations.AddField(
            model_name="projeto",
            name="publico",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="data_criacao",
            field=models.DateField(auto_now_add=True),
        ),
    ]
