# Generated by Django 4.2.5 on 2024-02-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_departamento_grupo_disciplina_aluno_professor_turma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto_Abstrato',
            fields=[
                ('cod_projeto_abstrato', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('projeto_abstrato_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.projeto_abstrato')),
                ('data_proposta', models.DateField()),
            ],
            bases=('app.projeto_abstrato',),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('projeto_abstrato_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.projeto_abstrato')),
                ('data_criacao', models.DateField()),
                ('status_projeto', models.CharField(choices=[('CO', 'Concluido'), ('CA', 'Cancelado'), ('SU', 'Suspenso'), ('EP', 'Em progresso')], default='EP', max_length=2)),
                ('cod_grupo', models.OneToOneField(on_delete=models.SET('Nao existe'), to='app.grupo')),
            ],
            bases=('app.projeto_abstrato',),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('cod_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=800)),
                ('status_avaliacao', models.CharField(choices=[('AP', 'Aprovado'), ('RE', 'Rejeitado'), ('ME', 'Melhorias')], max_length=2)),
                ('cod_proposta', models.OneToOneField(on_delete=models.SET('Nao existe'), to='app.proposta')),
            ],
        ),
    ]
