# Generated by Django 4.2.7 on 2024-03-02 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_projeto_tags_alter_proposta_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="grupo",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.grupo"
            ),
        ),
    ]
