@startuml
!include classes_comum.iuml

Aluno -- Projeto :  escolhe/trabalha num >
Aluno -- Turma   :  estuda numa >
Pessoa -- Buscador : faz buscas no >
Professor -- Turma : ensina numa >
Professor -- Projeto : propõe/supervisiona/aprova um >
Gestor -- Professor : gerencia >

hide Perfil
@enduml
