@startuml
folder Model{

    class Pessoa{
        Nome: String
        Idade: Int
        CEP: String
        Numero: String
        Complemento: String
        Telefone: String[]
        getNome()
        getCep()
    }

    class Professor {
        Matricula: String 
        getMatricula()
    }

    class Aluno {
        Matricula: String
        DataDeEntrada: Data
        getMatricula()
        getDataDeEntrada()
    }

    class Gestor {
        cadastrarProfessor()
        aprovarProposta()
    }

    class BaseProjeto {
        Titulo: String
        Descrição: String
        Status: String
        Criacao: Data
        Autor: Pessoa
        Membros Pessoa[]
        Tags: String[]
        Departamento: String
        Links: URL[]

        getTitulo()
        getDescricao()
        getProfessor()
        getMembros()
    }

    class Projeto {
        Entrega: Data
        ProductOwner: Pessoa

        informaRevisao()
        efetuarMudancas()
        persisteMudancas()
        efetuarProjeto()
        registrarMembros()
        verificarProjeto()
    }

    class Proposta{
        aprovarProposta()
        rejeitarProposta()
    }

    BaseProjeto <|-- Proposta
    BaseProjeto <|-- Projeto


    class Turma {
        Codigo: String
        Disciplina: String
        Departamento: String
        Horario: String
        NumeroSala: Int
        Semestre: Data
        getCodigo()
        getDisciplina()
        getDepartamento()
    }

    class Notificacao{
        data: Data
        tipo: String
    }

    Pessoa <|-- Professor
    Pessoa <|-- Aluno
    Pessoa <|-- Gestor
}

folder Control{
    
    class Buscador  {
     processarBusca()
     insereProjetoNoResultado()
     descartaProjetos()
     gerarResultados()
    }

    class VerificadorLogin{
        verificaddorCadastro()
    }

    class ControladorProjeto{
        tratarRevisao()
        encontrarProjeto()
    }

    class GerenciadorContas{
        enviaDados()
    }

    class ControladorTurma{
        registrarProposta()
    }
}

folder View{
    class TelaLogin{
        insereDados()
        informarValidez()
    }

    class TelaInicial{
        verificaNotificações()
        acessarProjeto()
        notificaAluno()
        acessarTurma()
        criarProjeto()
        verProjeto()
    }

    class TelaTurma{
        verPropostas()
        revisarProposta()
        escolherProjeto()
        proporProjeto()
    }

    class TelaRevisao{
        enviarRevisao()
    }

    class TelaBusca{
        informarTermoBusca()
        selecionarFiltros()
        confirmarBusca()
        informarResultados()
    }

    class TelaEscolhaProjeto{
        informarMembros()
        selecionarProjeto()
    }

    class TelaCadastro{
        insereDados()
    }

    class TelaProjeto{
        mudarProjeto()
        informarDados()
    }

    class TelaProposta{
        informarDados()
    }
}
@enduml
