@startuml
left to right direction
' Atores
:Pessoa: as Pessoa
:Aluno: as Aluno
:Professor: as Professor

' Extensões de atores
Pessoa <|-- Aluno
Pessoa <|-- Professor

rectangle "Projetorium" {
    (Consultar projeto) as ConsProj
    (Propor projeto) as PropProj
    (Ofertar projeto) as OfertProj
    (Manter projeto) as MantProj
    (Efetuar login) as EfetLog
    (Manter turma) as MantTurm
    (Manter aluno) as MantAlun
    (Avaliar proposta) as AvalProp
    (Escolher projeto) as EscProj
}

Pessoa -- ConsProj
Pessoa -- EfetLog

Aluno -- PropProj
Aluno -- EscProj
Aluno -- MantProj

Professor -- MantAlun
Professor -- MantTurm
Professor -- MantProj
Professor -- PropProj
Professor -- AvalProp
Professor -- OfertProj

@enduml

