@startuml
left to right direction
' Atores
:Aluno: as Aluno
:Professor: as Professor
:Interessado: as Interessado

rectangle "Projetorium" {
    (Alterar professor) as AltProf
    (Alterar aluno) as AltAlun

    (Criar turma) as CriTurm
    (Adicionar aluno) as AddAluno

    (Ofertar projeto) as OfertProj
    (Escolher projeto) as EscProj
    (Propor projeto) as PropProj
    (Alterar projeto) as AltProj
    (Avaliar proposta) as AvalProp

    (Consultar projeto) as ConsProj
}

Aluno -- PropProj
Aluno -- EscProj
Aluno -- AltAlun
Aluno -- ConsProj
Aluno -- AltProj

AltProf   -- Professor
CriTurm   -- Professor
PropProj  -- Professor 
AvalProp  -- Professor 
OfertProj -- Professor 
ConsProj  -- Professor 
AddAluno  -- Professor

ConsProj -- Interessado
@enduml

