@startuml
left to right direction
' Atores
:Aluno: as Aluno
:Professor: as Professor
:Interessado: as Interessado

rectangle "Projetorium" {
    (Consultar projeto) as ConsProj
    (Propor projeto) as PropProj
    (Ofertar projeto) as OfertProj
    (Manter projeto) as MantProj
    (Manter turma) as MantTurm
    (Manter aluno) as MantAlun
    (Avaliar proposta) as AvalProp
    (Escolher projeto) as EscProj
}

Aluno -- PropProj
Aluno -- EscProj
Aluno -- MantProj
Aluno -- MantAlun
Aluno -- ConsProj

MantAlun  -- Professor 
MantTurm  -- Professor 
MantProj  -- Professor 
PropProj  -- Professor 
AvalProp  -- Professor 
OfertProj -- Professor 
ConsProj  -- Professor 

ConsProj -- Interessado

@enduml

